### PR TITLE
Add more css properties, shorthands

### PR DESCRIPTION
**Pull request by lucyxiang**
Noticed that `ACCEPTABLE_CSS_PROPERTIES` is missing properties so adding some more (non exhaustive).

There’s a hodge podge of reasons why I choose these properties: I read through a bunch of “most common css properties / shorthands articles" and guesstimated what would be popular

### CODE REVIEW

**Comment by flavorjones** [comment]
@lucyxiang There are some failing tests because the existing shorthand CSS properties logic appears to have a bug that I'll need to dig into.

Can you break this up into two pull requests: one for the properties and keywords (which I think can be merged quickly), and another one for the additional shorthand properties (which I'll use to debug the failing tests)?

**Comment by flavorjones** [comment]
These properties and keywords look OK! There is one failing test, though, which looks like it's failing because the `position` property was previously disallowed but is now allowed. Are you able to update that test so it passes?

**Comment by factcondenser** [comment]
@flavorjones I'm continuing this work over in https://github.com/flavorjones/loofah/pull/283

**Comment by flavorjones** [comment]
Closing in favor of #283

**Pull request closed without merging**
