### PR TITLE
remove rbx-2 allow failure from .travis.yml

### PR DESCRIPTION
**Pull request by marutosi**

### CODE REVIEW

**Comment by marutosi** [comment]
What is status?

**Comment by flavorjones** [comment]
Hi @marutosi,

Thanks for submitting this PR.

Can you explain a bit about why you want to introduce rbx-2 into the "required" travis builds?

For context, nokogiri (a dependency of loofah) doesn't test against rbx-2 at all, and so until nokogiri supports rbx-2 I'm hesitant to introduce the opportunity for broken builds into the loofah codebase.

**Comment by marutosi** [comment]
There is no loofah and nokogiri support policy document.
Broken Jruby Rails 4.2 is serious problem for Redmine.
 I am waiting #88 and relating nokogori PRs long time.

**Comment by marutosi** [comment]
> Broken Jruby Rails 4.2 is serious problem for Redmine.

http://www.redmine.org/projects/redmine/wiki/RedmineInstall#Ruby-interpreter

**Comment by flavorjones** [comment]
I am very sorry, but I do not understand what jruby support has to do with this pull request, which adds a requirement for rubinius-2 support. Can you help me understand?

**Comment by marutosi** [comment]
If you keep rbx-2 allow_failures, why do not merge https://github.com/sparklemotion/nokogiri/pull/1319 and https://github.com/sparklemotion/nokogiri/pull/1320 and allow failure nokogiri?
I cannot understand loofah and nokogiri support policy.

**Comment by flavorjones** [comment]
@marutosi I understand that you are frustrated with JRuby support. Thank you for pointing out the related PRs that will address the blockers.

However, I do not understand what this PR has to do with JRuby support, as it deals only with adding rbx-2 as a required build platform. Can you please address my original questions about rbx-2?

**Comment by marutosi** [comment]
> Can you please address my original questions about rbx-2?

You can see rbx-2 tests passed.
https://travis-ci.org/flavorjones/loofah/builds/80234142
https://travis-ci.org/flavorjones/loofah/builds/76027555
https://travis-ci.org/flavorjones/loofah/builds/76026769

**Comment by flavorjones** [comment]
It sounds like you're asking if I'm prepared to support an additional platform, Rubinius 2.

Based on your feedback above, it's clear that I'm doing a terrible job of supporting the existing platforms, and so I'm going to decline to accept this pull request.

**Pull request closed without merging**
