### PR TITLE
Use safelist(s), allowlist(s) where applicable

### PR DESCRIPTION
**Pull request by JuanitoFatas**
This Pull Request updates:
- terminology in the codebase
- rake task changed to `rake generate_allowlists`

Safelist, allowlist is easier to understand and less offensive. 

[Original motivation](https://github.com/rails/rails/issues/33677), other community efforts examples:

- https://github.com/rails/rails/pull/33681
- https://github.com/graphiti-api/graphiti/pull/10
- https://github.com/rails/rails/pull/33718
- https://github.com/ruby/psych/pull/378
- https://github.com/ruby/ruby/pull/2008
- https://github.com/ruby/ruby/pull/2009
- https://github.com/rubocop-hq/rubocop/pull/6464
- https://github.com/rubygems/rubygems/pull/2463
- https://github.com/dtao/safe_yaml/pull/93
- https://github.com/rack/rack/pull/1314
- https://github.com/rubocop-hq/rubocop/pull/6466
- https://github.com/rubocop-hq/rubocop/pull/6467
- https://github.com/rspec/rspec-core/pull/2576
- https://github.com/rspec/rspec-expectations/pull/1083
- https://github.com/rspec/rspec-mocks/pull/1246
- https://github.com/rspec/rspec-support/pull/356
- https://github.com/pry/pry/pull/1874
- https://github.com/pry/pry/pull/1875

### CODE REVIEW

**Comment by flavorjones** [comment]
Apologies for the long response time here -- the last few weeks have been hectic for me. This is still on my TODO list and I intend to get to it as soon as I can.

**Comment by flavorjones** [comment]
Just an update: I'm struggling to find time to work on OSS; this is still something I'm very keen to do, so thanks for your patience.

**Comment by flavorjones** [comment]
Hi! I apologize for this going so long without review. I'm dedicating some time this week to my open source projects and will spend some time with this PR. Thank you again for sending such a thoughtful PR.

**Comment by JuanitoFatas** [comment]
Closing in favor of #164.

**Comment by flavorjones** [comment]
v2.3.0 has been released.

**Comment by coreyward** [comment]
Offensive? “Blacklist” is not race related, either in origin or context. “Whitelist“ is it’s opposite. https://www.reddit.com/r/AskHistorians/comments/866ynp/what_are_the_origins_of_the_words_blacklist_and/

**Pull request closed without merging**
