### PR TITLE
Allow select URI Data Mediatypes

### PR DESCRIPTION
**Pull request by mrpasquini**
How is this for a start at resolving issue #101 ?

- Allows data as a protocol but then applies a filter on allowed mediatypes
- Is not checking/validating the optional `;base64` part of `data:<mediatype>[;base64],<data>`
- Is not checking/validating the data/data encoding

### CODE REVIEW

**Comment by mrpasquini** [comment]
Hey @flavorjones, Can you take a look and comment?

**Comment by nguyenmighty** [comment]
Will this commit be in 2.1.0 version?

**Comment by mrpasquini** [comment]
Ping @flavorjones 
Happy to make this more generically support partial protocols if that is preferred.

**Comment by PratheepV** [comment]
+1

**Comment by drosboro** [comment]
+1 This would be very helpful, as a starting point.

**Comment by flavorjones** [comment]
Sorry for the long silence; this PR looks mostly good. I'd like to add a negative test and then I'll merge it. Working on it now.

**Comment by flavorjones** [comment]
Merged manually! Will be in the next release. Thanks so much for your contribution and patience!

**Comment by mrpasquini** [comment]
Awesome, Thanks!

**Comment by flavorjones** [comment]
Is in 2.1.0 that just shipped.

**Pull request closed without merging**
