### PR TITLE
Allow HTML property: contenteditable

### PR DESCRIPTION
**Pull request by andreynering**

### CODE REVIEW

**Comment by flavorjones** [comment]
Hi, @andreynering. Thank you for subnitting this PR, and apologies for the delay in replying (this week has been crazy for me).

I'm going to spend some time this weekend on OSS and will likely merge this then.

**Comment by ftwasilewski** [comment]
Nice, I'm facing the same issue here

**Comment by andreynering** [comment]
Ping @flavorjones 

Any chance of merging this?

**Comment by flavorjones** [comment]
Apologies for the slow response. I've merged this and it will be in v2.3.0. Thank you!

**Comment by flavorjones** [comment]
v2.3.0 has been released.

**Comment by andreynering** [comment]
@flavorjones Thanks!

**Pull request merged**
