### PR TITLE
Add border-style keywords

### PR DESCRIPTION
**Pull request by tarcisiozf**
Hi, I'm having some issues when trying to sanitize elements with border-style. I've added the missing keywords following the spec: https://developer.mozilla.org/en-US/docs/Web/CSS/border-style

### CODE REVIEW

**Comment by flavorjones** [comment]
@tarcisiozf Thank you for submitting this! Looks great, just had one request which was to follow the convention of listing attributes and keywords in alphabetical order.

**Comment by flavorjones** [comment]
@tarcisiozf Just wanted to check if you are open to making the change I requested?

**Comment by tarcisiozf** [comment]
@flavorjones sorry for taking so long to answer, I'll do the requested changes.

**Comment by tarcisiozf** [comment]
@flavorjones done, did I miss anything else?

**Comment by flavorjones** [comment]
Looks good, thank you! Merging.

**Comment by flavorjones** [comment]
I've shipped loofah v2.6.0 with this change in it, and credited you in the CHANGELOG. Thank you!

**Pull request merged**
