### PR TITLE
Added "fax" to acceptable protocols based on rfc2806.

### PR DESCRIPTION
**Pull request by cjba7**
[rfc2806](https://www.rfc-editor.org/rfc/rfc2806#section-2.3) and its superseding standards state `fax` as an acceptable scheme.

### CODE REVIEW

**Comment by flavorjones** [comment]
Hi! Thanks for submitting this. Looking at the RFC, I also see the `modem` scheme. Is there any reason we shouldn't add that to the safelist while we're here?

**Comment by cjba7** [comment]
@flavorjones makes sense. I have just added it.

**Comment by flavorjones** [comment]
Thank you! I've kicked off CI again, looks like the 2.5 failure is unrelated so ignore it. I'll merge when I get a block of time (later today?) and hopefully cut a release this week.

**Comment by cjba7** [comment]
Sounds good. Thanks for maintaining it!

**Comment by flavorjones** [comment]
This has been released in [Release 2.20.0 / 2023-04-01 · flavorjones/loofah](https://github.com/flavorjones/loofah/releases/tag/v2.20.0).

**Pull request merged**
